### ISSUE TITLE
"Corvid Twenty" incorrect requirement

### ISSUE THREAD

**Issue by Tymon13** [Jacorb90/Dist-Inc.github.io#11]
Description says that we need at least one of each of the 10 Pathogen upgrades, but it actually requires PTH_AMT (which is 15). I suppose they were expanded at some point and achievement requirement was not updated?

It's verified at line `functions/achievements.js:56`

**Comment by Jacorb90** [comment]
> Description says that we need at least one of each of the 10 Pathogen upgrades, but it actually requires PTH_AMT (which is 15). I suppose they were expanded at some point and achievement requirement was not updated?
> 
> It's verified at line `functions/achievements.js:56`

Yes, I'm aware of this bug... I will fix it in the next major update release.
For now, the 1% boost to Pathogen gain is not really that major, so until it is fixed, it should be fine, but thanks for reporting regardless.
