### ISSUE TITLE
Minor Requests - button color and text, percentage complete

### ISSUE THREAD

**Issue by Falthazar** [Jacorb90/Dist-Inc.github.io#19]
Really liking the game so far, but there are two minor requests.
In dark mode, the light green button behind white text makes it really hard to read. You may want to make the button colors a little darker.

The other thing is the percent complete for unlocks and stuff seems to be logarithmic? So if you need something like 1 ly to unlock something and you have .5 lys, it'll say something around 90% there, when you're really only 50%. I think you were trying to make it match scaling a little, in that the last .5 lys is a lot faster to get than the first .5, but I think it's less helpful this way. Maybe make it an option to change?

Lastly, more of a feature request, but can you add [engineering notation](https://en.wikipedia.org/wiki/Engineering_notation) as well as scientific?

**Comment by Jacorb90** [comment]
1. The light green thing in dark mode will be patched for the next update (already known & figured out)
2. As for the percentage completion thing, i'll work on that...
3. Engineering notation will be added as well...

Thanks for the minor requests, they are quite helpful!

**Comment by Jacorb90** [comment]
These fixes have been figured out for the next update, so I will close this issue, but thanks for letting me know regardless!
