### ISSUE TITLE
Feature Request - List what is boosting what

### ISSUE THREAD

**Issue by Falthazar** [Jacorb90/Dist-Inc.github.io#20]
When you get to the later stages, it's hard to see what is being boosted by what. 

I have gotten to Elementaries, but it's hard to know what to set my Fermions too, to get the most out of them. It'd be helpful to see something along the lines of
You have e896 K rockets (+e896 K/sec) ... 
Boosted by: 
Inf x;x - 3x
Inf x;x - e^12
Fermions - e^x
Achievements - x
etc.

Might be a better way of doing that? 
The real issue is I'm not always sure what's holding me back the most in getting more EP, knowledge gain? cadavers? etc.

**Comment by Jacorb90** [comment]
I would like to agree but there a few things that would make this change a little... difficult, such as the following:
    1. Where would this system be displayed?
    2. I would need to add this for every single upgrade, achievement, and feature in the game
    3. I don't think doing all of that is worth the visual help.

As for the whole EP thing, I would need to know more about your situation. 
If you would like more help in that regard, come ask in Distance Incremental's Discord server (link is at the bottom of the options menu in-game).

**Comment by Falthazar** [comment]
Yea, I realize this would be incredibly difficult. I still think it'd be a little helpful, though maybe I should see how other similar incremental handle this. Haven't played Antimatter in a year or more.
As for EP, I figured that out - just wait a lot longer between resets. Now I have the issue of not enough distance, though I'm pretty close to unlocking theory. 
You can just close this issue, and I'll check out the discord!

**Comment by Jacorb90** [comment]
Alrighty, thanks for letting me know!
