### ISSUE TITLE
Lepton buffs have a negative increase instead of positive

### ISSUE THREAD

**Issue by AsenIvanov** [Jacorb90/Dist-Inc.github.io#23]
Hi again,
The lepton effects for stronger perks, pathogen upgrades and derivative boost actually lower these effects instead of increase them.    Not sure what the magnitude of the decrease is though. 

Thanks for taking care of the auto-elementary issue as well earlier. 

Here is a save if it helps https://pastebin.com/ykJa8V17

**Comment by Jacorb90** [comment]
Oh my god I can't believe I missed this... thanks so much for letting me know, this will be fixed for the next major update.
I'm gonna close this because I have it written on my "to do list" for Distance Incremental stuff, so I will get to it before v1.7 release.
